### ISSUE TITLE
想问一下作者使用的zxing 是哪个版本的呢？

### ISSUE THREAD

**Issue by tianshaokai** [yipianfengye/android-zxingLibrary#1]
作者是否考虑增加以下功能呢？
1. 增加识别条形功能
2. 在自定义view 中自定义加入四角线，和中间来回滚动线
3. 创建二维码和带logo 的二维码
4. 6.0 系统运行时权限处理

**Comment by yipianfengye** [comment]
很赞，接下来会考虑添加这些功能

**Comment by yipianfengye** [comment]
1 条形码默认可以识别；
2 自定义View，可自定义加入四脚线和来回滚动县；
3 已经支持创建二维码和带Logo的二维码；
4 类库targetSDKVersion为22，在Android6.0上没有了问题，后续会适配6.0的权限
