### ISSUE TITLE
1.7依赖有问题

### ISSUE THREAD

**Issue by heygays** [yipianfengye/android-zxingLibrary#10]
似乎你library的Manifest清单里的Application存在name（com.uuzuche.lib_zxing.ZApplication）字段，依赖会报错，我下载了library来依赖去掉就可以了。

**Comment by yipianfengye** [comment]
恩？去掉之后你还可以正常显示默认的扫描框么？

**Comment by heygays** [comment]
可以的

**Comment by yipianfengye** [comment]
这是在module中自定义了Application，按道理不应该出错的啊，你是报什么错误？

**Comment by timlusailing** [comment]
在自己的AndroidManifest.xml中<application里加入tools:replace="android:name"就好了

**Comment by timlusailing** [comment]
作者兄弟！在我发起的讨论里给你留言了，你看是不是有那样的问题啊

**Comment by yipianfengye** [comment]
sorry，我迷糊了，不好意思，compile已经更新了，你试试1.8呢

**Comment by timlusailing** [comment]
"二维码图片在恰好或接近布满扫描框时还是不能识别出来，需要拉远点才能识别出来",这个问题还是有啊

**Comment by yipianfengye** [comment]
这个还在优化，最近事情比较多，回复的比较慢
