### ISSUE TITLE
请问怎么样用前置摄像头扫描，谢谢。

### ISSUE THREAD

**Issue by topCard** [yipianfengye/android-zxingLibrary#143]

**Comment by topCard** [comment]
调用前置摄像头的方法：
1.下载源码，在项目里引用，修改camera下面的CameraManager文件：
![image](https://user-images.githubusercontent.com/29538781/29392225-085e07ec-832f-11e7-8b9b-b66d88030137.png)
2.修改openDriver方法的camera = Camera.open();改成camera = Camera.open(Camera.CameraInfo.CAMERA_FACING_FRONT);
![image](https://user-images.githubusercontent.com/29538781/29392379-1d0d2654-8330-11e7-8b1c-a06dae15bebc.png)
这是默认为前置摄像头扫描二维码；
也写了一个可以动态设置摄像头调用的：
![image](https://user-images.githubusercontent.com/29538781/29392483-adb9ccde-8330-11e7-9128-022858443b19.png)
然后CaptureFragment修改：
![image](https://user-images.githubusercontent.com/29538781/29392526-ff57912a-8330-11e7-9c6c-ba705bb814c8.png)

![image](https://user-images.githubusercontent.com/29538781/29392541-22e3050c-8331-11e7-8c26-acb11e44bebe.png)
使用时直接传参数就可以了
![image](https://user-images.githubusercontent.com/29538781/29392566-527d263a-8331-11e7-93e7-1cf9b104187d.png)

**Comment by wjy18800106134** [comment]
我也遇到了这个问题。
我在用的时候直接引用了 lib-zxing 这个库，这样就可以修改其中的代码。
然后找到 CameraManager 这个类，里面有个 openDriver 这个方法，获取camera的代码就在这里面。
注释掉camera = Camera.open();这句，然后修改成以下的代码就可以了。
希望对你有帮助
//            camera = Camera.open();
//            -------------修改为打开前置摄像头
            int cameraCount = 0;
            Camera.CameraInfo cameraInfo = new Camera.CameraInfo();
            cameraCount = Camera.getNumberOfCameras(); // get cameras number

            for (int camIdx = 0; camIdx < cameraCount; camIdx++) {
                Camera.getCameraInfo(camIdx, cameraInfo); // get camerainfo
                if (cameraInfo.facing == Camera.CameraInfo.CAMERA_FACING_FRONT) { // 代表摄像头的方位，目前有定义值两个分别为CAMERA_FACING_FRONT前置和CAMERA_FACING_BACK后置
                    try {
                        camera = Camera.open(camIdx);
                    } catch (RuntimeException e) {
                        e.printStackTrace();
                    }
                }
            }
//            -------------修改为打开前置摄像头
