### ISSUE TITLE
相机 画面一直是镜像

### ISSUE THREAD

**Issue by ybADMIN** [yipianfengye/android-zxingLibrary#149]
相机拍摄出来的画面是反的

**Comment by CXJean** [comment]
如果是这样的话，你拿真机测是没问题的，模拟器出来是这个效果


------------------ 原始邮件 ------------------
发件人: "sunny";<notifications@github.com>;
发送时间: 2017年10月12日(星期四) 下午2:52
收件人: "yipianfengye/android-zxingLibrary"<android-zxingLibrary@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [yipianfengye/android-zxingLibrary] 相机 画面一直是镜像 (#149)




Closed #149.

**Comment by CXJean** [comment]
http://blog.csdn.net/qq_23547831/article/details/52037710
可以看看这个，写的很详细


------------------ 原始邮件 ------------------
发件人: "sunny";<notifications@github.com>;
发送时间: 2017年10月12日(星期四) 下午2:52
收件人: "yipianfengye/android-zxingLibrary"<android-zxingLibrary@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [yipianfengye/android-zxingLibrary] 相机 画面一直是镜像 (#149)




Closed #149.
