### ISSUE TITLE
更新到as3.0，后出现Error:Error converting bytecode to dex: Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/client/result/EmailAddressParsedResult;

### ISSUE THREAD

**Issue by ThreeHands** [yipianfengye/android-zxingLibrary#165]
Warning:Ignoring InnerClasses attribute for an anonymous inner class
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/client/result/EmailAddressParsedResult;
Error:com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/client/result/EmailAddressParsedResult;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/oned/rss/expanded/decoders/GeneralAppIdDecoder;
Error:com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/oned/rss/expanded/decoders/GeneralAppIdDecoder;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/oned/rss/expanded/decoders/GeneralAppIdDecoder;

**Comment by 18300072348** [comment]
@ThreeHands 这个问题你怎么解决的

**Comment by ThreeHands** [comment]
这个是包多引用了，你看一下Gradle Console的日志信息，看是什么包多引用了，我的是support.v4包，在一个project中，包括library，只能编译一个类型的包，也就是说，在module中和library中只能有一个相同的包，我在module的libs文件中和library的libs文件中都放了support.v4包，导致了该问题。如果有多引用的，可以删掉一个，比如，support.v4包，可以把support.v4包放在library中，然后在app目录下的build.gradle文件中添加complie project(':xxxxx')来引用到support.v4包。试一下，如果不行的把Gradle Console的日志贴出来帮你看看。

**Comment by 18300072348** [comment]
@ThreeHands 但是之前2.3.3没有这个问题呢

**Comment by ThreeHands** [comment]
我忘了之前是什么样子，可能之前版本可以忽略掉这个，更新到3.0后gradle编译更严格了。
