### ISSUE TITLE
集成对二维码图片的解析功能 中的CodeUtils.analyzeBitmap的使用问题

### ISSUE THREAD

**Issue by tuionf** [yipianfengye/android-zxingLibrary#17]
在readme文件中说道集成对二维码图片的解析功能 中的CodeUtils.analyzeBitmap的使用，第一个参数写的是Bitmap 对象，这个会报错的，查看api显示应该是String path 对象，这可能是笔误吧。

我看了一下源码，此处应该是uri.getPath()，而不是mBitmap

**Comment by jp1017** [comment]
第一个参数应该是图片文件的绝对路径，https://github.com/yipianfengye/android-zxingLibrary/pull/15/files

**Comment by tuionf** [comment]
OK
