### ISSUE TITLE
lib_zxing 里面的 AndroidManifest.xml 文件精简

### ISSUE THREAD

**Issue by jp1017** [yipianfengye/android-zxingLibrary#19]
`AndroidManifest.xml` 文件只要包名就可以的，权限什么的在app里申请就好

否则会出现此问题：https://github.com/yipianfengye/android-zxingLibrary/issues/10

毕竟这是一个库

**Comment by jsxGitHub** [comment]
自己的AndroidManifest.xml  文件中如果配置了android：name ＝ application 属性 。会产生冲突

**Comment by haiker2011** [comment]
遇到了同样的问题，有什么好的解决办法吗？

**Comment by jsxGitHub** [comment]
把作者的library 不以库的形式使用。  引用为自己的代码 ，然后可以修改源代码了，把初始化方法写在自己的application方法里就行了

**Comment by jp1017** [comment]
楼上正解，我暂时是这么用的，等 @yipianfengye  更新呢 :smile:

**Comment by jsxGitHub** [comment]
我这种菜鸟只会改改bug
