### ISSUE TITLE
解析相册中二维码图片的问题

### ISSUE THREAD

**Issue by MirrorFlower** [yipianfengye/android-zxingLibrary#22]
解析图库中二维码图片代码部分的这句： CodeUtils.analyzeBitmap(mBitmap, new CodeUtils.AnalyzeCallback()  第一个参数是bitmap ，为何CodeUtils中的analyzeBitmap的静态方法第一个传的参数却是String类型的？报错了~

**Comment by yipianfengye** [comment]
版本问题，你更新一下compile的版本
