### ISSUE TITLE
ZApplication与自定义Application冲突

### ISSUE THREAD

**Issue by tonyyang123** [yipianfengye/android-zxingLibrary#25]
compile 'cn.yipianfengye.android:zxing-library:1.8' 导入项目后发现与自定义application冲突，
使用tools:replace="android:name"避免了冲突，但是会报错Both dimensions must be greater than 0。
直接导入项目作为module使用，删除ZApplication类，将ZApplication的initDisplayOpinion方法作为初始化方法在自定义Application中调用，运行正常。
建议lib中的ZApplication类修改为不继承自Application类，作为初始化类提供initDisplayOpinion方法给使用者在自定义Application中调用

**Comment by Ianlyly** [comment]
同样遇到这个问题，望答复

**Comment by tonyyang123** [comment]
将lib-zxing作为module导入到项目中使用，ZApplication类不继承Application类，在自定义Application中调用ZApplication.initDisplayOpinion()

**Comment by Ianlyly** [comment]
暂时先用这个办法，谢谢

**Comment by yipianfengye** [comment]
已改正
