### ISSUE TITLE
可以考虑兼容一下androidX吗

### ISSUE THREAD

**Issue by wu9007** [yipianfengye/android-zxingLibrary#250]
可以考虑兼容一下androidX哦~

**Comment by liudaohong** [comment]
自己报包下下来 到自己项目自己适配吧

**Comment by wu9007** [comment]
哈哈哈 英雄所见略同 提完issue我就适配了 https://github.com/leyan95/android-zxingLibrary

**Comment by liudaohong** [comment]
那要是换框架要疯掉

**Comment by zhanshen1373** [comment]
> 可以考虑兼容一下androidX哦~

怎么使用兼容androidx的呀。你是自己项目中依赖的自己的吗，有没有这种东西 compile 'cn.yipianfengye.android:zxing-library:2.2'
