### ISSUE TITLE
部分二维码扫描识别不了

### ISSUE THREAD

**Issue by wangyuan0217** [yipianfengye/android-zxingLibrary#255]
![1572512210](https://user-images.githubusercontent.com/12730214/68006001-1fd5e300-fcb2-11e9-8a1f-fe33005ad7e7.png)
如上图（二维码对应的内容为-----http://172.16.30.98/app/ubgogo/#/welfareDetail?taskId=1526028407387967488），扫描识别不了；

备注：
![image](https://user-images.githubusercontent.com/12730214/68006051-4dbb2780-fcb2-11e9-93a1-02e56b5c21e0.png)
草料这个同样的内容生成二维码和生成网址码，生成二维码方式生成的码该库可以识别，但是生成网址码该库就无法识别（微信和浏览器的扫一扫都可以识别的）。不知道草料这两个生成方式有什么区别，为什么会导致识别不了。

**Comment by ailiwean** [comment]
@wangyuan0217 灰度密集不一致导致的，  搜下NBZxing可以扫到

**Comment by wangyuan0217** [comment]
ths
