### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by hjja1** [yipianfengye/android-zxingLibrary#26]
不管用自带的CaptureActivity 还是自定义的activity   Framelayout显示都是黑屏。。该怎么解决呢

**Comment by smileysx** [comment]
我刚才还有使用CaptureActivity，不会出现黑屏

**Comment by hjja1** [comment]
- -可是我刚刚新建的application 都出现这个问题。。你compile的还是导包的

**Comment by smileysx** [comment]
compile

**Comment by hjja1** [comment]
这就奇怪了。。我跑跑看下的demo试试

**Comment by hjja1** [comment]
不行 demo也这样。。。你手机系统多少的  难道因为我6.0？

**Comment by hjja1** [comment]
解决了 权限问题。6.0要么动态权限 要么sdkversion设置下 麻蛋- - 测试机全6.0的  坑了我好久
