### ISSUE TITLE
二维码图片的解析功能 代码有问题啊

### ISSUE THREAD

**Issue by hong940619** [yipianfengye/android-zxingLibrary#29]
```
                Bitmap mBitmap = MediaStore.Images.Media.getBitmap(cr, uri);//显得到bitmap图片
                CodeUtils.analyzeBitmap(mBitmap, new CodeUtils.AnalyzeCallback() {
                    @Override
                    public void onAnalyzeSuccess(Bitmap mBitmap, String result) {
                        Toast.makeText(MainActivity.this, "解析结果:" + result, Toast.LENGTH_LONG).show();
                    }
```

传入的是一个bitmanp,但是函数接收的是一个字符串类型啊，怎么解决啊？？

**Comment by jp1017** [comment]
传入的是文件绝对地址字符串啊，demo里有的

我也有你这需求，根据bitmap识别，自己改了下，一会把这个写到ｐｒ，更新下吧，哈哈

**Comment by jp1017** [comment]
@yipianfengye 已提交pr

@hong940619  可以参考这里：

https://github.com/jp1017/android-zxingLibrary/blob/master/lib-zxing/src/main/java/com/uuzuche/lib_zxing/activity/CodeUtils.java

**Comment by alienzh** [comment]
你好，compile 'cn.yipianfengye.android:zxing-library:2.1'这个里面的CodeUtil还是没有analyzeBitmap(Bitmap bitmap, AnalyzeCallback analyzeCallback) 这个方法的啊

**Comment by xj913492952** [comment]
我的图片绝对路径没问题，但还是解析失败，为什么
