### ISSUE TITLE
小米5测试打开扫描界面黑屏

### ISSUE THREAD

**Issue by MaskEgo** [yipianfengye/android-zxingLibrary#32]
参照你的demo写的，不过，测试按钮打开扫描是在fragment里的

**Comment by jp1017** [comment]
6.0需要配置权限哦

**Comment by MaskEgo** [comment]
配置哪个权限啊- -，是6.0系统。貌似要动态获取权限。。不知道怎么搞

**Comment by jp1017** [comment]
这个网上教程太多了哈 :smile:

**Comment by MaskEgo** [comment]
好哒，我去看看__O(∩_∩)O

**Comment by MaskEgo** [comment]
亲爱的作者，我还是没能解决，，这个错Jni的 ，不知道怎么弄，能不能帮帮我
 E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0

**Comment by xm3366336** [comment]
怎么解决的，吱一声咯，谢谢

**Comment by yongleWU006** [comment]
@MaskEgo 我也碰到这问题问题怎么解决的

**Comment by luyun181** [comment]
E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0


这个怎么解决的？
