### ISSUE TITLE
打开扫描界面黑屏

### ISSUE THREAD

**Issue by Hao-Kid** [yipianfengye/android-zxingLibrary#34]
一加3手机

**Comment by yipianfengye** [comment]
是Android M么？需要申请权限

**Comment by MRwangqi** [comment]
我的打开也是黑屏的，小米系统的，4.4.2的系统

**Comment by threezj** [comment]
需要权限。
 <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-permission android:name="android.permission.VIBRATE"/>
