### ISSUE TITLE
请问这是基于zxing的哪个版本提取的啊？

### ISSUE THREAD

**Issue by jayleco** [yipianfengye/android-zxingLibrary#36]
作者能不能在每次更新版本的后面注明下基于的zxing版本啊？

**Comment by leonck** [comment]
同问 是基于zxing的哪个版本提取的啊？

**Comment by yipianfengye** [comment]
3.0.1

**Comment by liupeng110** [comment]
1.8
https://github.com/yipianfengye/android-zxingLibrary/commit/23f5fb7d06d0765e50998e632bb28b9723b7a213
