### ISSUE TITLE
扫描二维码的界面，显示的时候整体被横向压缩

### ISSUE THREAD

**Issue by rongdongliu** [yipianfengye/android-zxingLibrary#4]
普通扫描的时候，横向压缩，手机红米2a增强版，Android 5.1.1 ui8

**Comment by yipianfengye** [comment]
已修复，更新compile版本即可

**Comment by rongdongliu** [comment]
楼主你好，关注横向挤压的问题，您是怎么处理的。能具体点吗，哪个类？那行代码开始？谢谢啦

**Comment by yipianfengye** [comment]
可参考：http://blog.csdn.net/aaawqqq/article/details/24852915
