### ISSUE TITLE
华为 Mate8 打开黑屏

### ISSUE THREAD

**Issue by changjiashuai** [yipianfengye/android-zxingLibrary#45]
W/CameraBase: An error occurred while connecting to camera: 0
E/Camera-JNI: android_hardware_Camera_native_setup Error: -1 
E/Camera: Camera new cameraInitNormal:-1

**Comment by weishd** [comment]
三星S5，打开也是黑屏。

**Comment by xiaoyulu1105** [comment]
我的手机是oppoR825也是黑屏呜呜呜

**Comment by lieweisi** [comment]
我的乐2也是黑屏

**Comment by yipianfengye** [comment]
需要在自己的module中申请权限
