### ISSUE TITLE
compileSdkVersion为22编译不通过

### ISSUE THREAD

**Issue by ysygit123** [yipianfengye/android-zxingLibrary#5]
1. 我将app和lib-zxing中的build.gradle文件中的编译sdk改为22，相应的tools编译工具改为22.0.1、dependencies中的支持包也改为22.2.1, 无法通过编译，一直values-23中的资源找不到。

2. 都没用23的编译，为什么会报这个错误？非常感谢

**Comment by yipianfengye** [comment]
如果你更改compile的版本，也需要修改：
compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
的版本

**Comment by yipianfengye** [comment]
改正

**Comment by ysygit123** [comment]
已经按照你说的改过了，还是编 译不通过，仍然非常感谢。我这边把直接把zxingLibrary作为库项目依赖了，现在可以使用了
