### ISSUE TITLE
扫描 ,带自定义的带logo的二维码图片 ,扫不出来 . . 

### ISSUE THREAD

**Issue by wooshlele** [yipianfengye/android-zxingLibrary#6]
如图

**Comment by wooshlele** [comment]
刚刚我吧扫描框,调大了, 就可以扫出来了 .,,不好意思楼主 . ..

**Comment by yipianfengye** [comment]
呵呵，正想问你没看到图呢

**Comment by wooshlele** [comment]
刚开始也想到底是什么问题,ios说都没有问题,然后我去看微信的扫描框,, 微信是秒扫,,我无意观察到微信的扫描框挺大,,我抱着试试的态度, 原来是这么回事,哈哈 . .
