### ISSUE TITLE
发现距离太近时无法解析出来，大神能改进下吗

### ISSUE THREAD

**Issue by timlusailing** [yipianfengye/android-zxingLibrary#9]
大神的作品很棒！相信你做得会越来越精致，我顶你！

**Comment by timlusailing** [comment]
发现是与分辨率有关系，低分辨率手机正常，高分辨率手机需要离得很远才能识别出来，如果加入分辨率与取景框的适配就更好了！

**Comment by yipianfengye** [comment]
多谢，我更改一下

**Comment by yipianfengye** [comment]
已经更改了默认扫描框的大小，默认长宽为屏幕宽度的一般，自定义属性更改属性为dimension

**Comment by timlusailing** [comment]
牛！！！实在佩服你的神速！

**Comment by yipianfengye** [comment]
哈哈，正好看到

**Comment by timlusailing** [comment]
今天用了新版本，扫描框可以自定义了，棒！不过发现二维码图片在恰好或接近布满扫描框时还是不能识别出来，需要拉远点才能识别出来，我看微信扫一扫是可以的，你能改进下吗？

**Comment by timlusailing** [comment]
网上查了一下，http://blog.csdn.net/jifashihan/article/details/50623596，http://download.csdn.net/detail/rememberdewo/8132245，有人这样改进的，不过我没试，你看有没有用，还有我是在魅族note2上测试的，设备密度是3，比较高的
